#version: '3.1'
#services:
# my_dfile_cont
#build:
# contex: .
# dockerfile : Dockerfile


version: "3.1"
services: 
  my_dfile_cont:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
